# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_body', models.TextField()),
                ('publish_date', models.DateTimeField(verbose_name='reg_date')),
                ('slug', models.SlugField(max_length=200)),
                ('abrove', models.BooleanField()),
            ],
        ),
    ]
