# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('cat_date_pub', models.DateTimeField(verbose_name='date_pub')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_descr', models.CharField(default='no comment', max_length=1000)),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('comment_usrname', models.CharField(max_length=100)),
                ('comment_reply', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Inappropriate_words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inappr_wrd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('post_body', models.TextField()),
                ('image', models.ImageField(upload_to=b'')),
                ('publish_date', models.DateTimeField(verbose_name='reg_date')),
                ('approve', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categories')),
                ('curr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment_section',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Posts'),
        ),
    ]
