# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postes',
            new_name='Posts',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='abrove',
            new_name='aprove',
        ),
    ]
