# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
