# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170205_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='aprove',
            new_name='approve',
        ),
    ]
